# Generated by Django 4.0.4 on 2022-06-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='phone_number',
            field=models.IntegerField(max_length=50),
        ),
    ]
