# Generated by Django 4.0.4 on 2022-06-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_food', '0002_alter_booktable_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
