# Generated by Django 4.0.4 on 2022-06-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_food', '0003_alter_booktable_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='birthday',
            field=models.DateField(),
        ),
    ]
